# 애플리케이션 이름
spring.application.name=boot

# 외장 WAS 사용
spring.main.web-application-type=none

# 톰캣 포트 변경
server.port=9090

# context path 설정 (default : "/" -> context path 없음)
# server.servlet.context-path=/boot

# JSP 설정
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp
server.servlet.jsp.init-parameters.development=true  # JSP 수정하면 곧바로 반영

# 데이터베이스 설정

# Using OracleDriver
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

# Using Log4jdbc-log4j2
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:oracle:thin:@localhost:1521:xe

spring.datasource.username=green
spring.datasource.password=green

# timezone 설정
spring.datasource.hikari.data-source-properties.oracle.jdbc.timezoneAsRegion=false

# 마이바티스 설정
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.min.boot.dto
mybatis.mapper-locations=mybatis/mapper/*.xml

# jsessionid 쿠키 값이 주소 창에 붙는 문제 방지 (http://localhost:9090/boot?jsessionid=F628e7...)
server.servlet.session.tracking-modes=cookie

# 첨부 파일 설정
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

# 세션 시간 (1800 seconds = 30 minutes)
server.servlet.session.timeout=1800

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=forspringlec@gmail.com
spring.mail.password=****
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
